type: app
info:
  name: contract-mesh/cli-tool
features:
  cli:
    root:
      $contract-ref: ./contracts/root.docopt
    validate:
      $contract-ref: ./contracts/validate.docopt
    render:
      $contract-ref: ./contracts/render.docopt
    codegen:
      $contract-ref: ./contracts/codegen.docopt
dependencies:
  contract-mesh/api:
    openapi:
      - GET /v1/entities